web-app/hw1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('rideSharing.urls')),
]

web-app/rideSharing/urls.py
from django.urls import path    
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required




urlpatterns = [
    # system entrance and exit
    path('', auth_views.LoginView.as_view(template_name='rideSharing/login.html'), name='login'),  # enter login page first
    path('logout/', auth_views.LogoutView.as_view(template_name='rideSharing/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    
    # home page menu
    path('home/', views.home, name='rideSharing-home'),
    path('editProfile/', views.editProfile, name='editProfile'),

    # all orders
    path('showAllOrders/', views.showAllOrders, name='showAllOrders'),
    path('showOwnerOrders/', views.showOwnerOrders, name='showOwnerOrders'),
    path('showDriverOrders/', views.showDriverOrders, name='showDriverOrders'),
    path('showSharerOrders/', views.showSharerOrders, name='showSharerOrders'),
    path('completeDriverOrders/<int:id>', views.completeDriverOrders, name='completeDriverOrders'),
    path('editOwnerOrders/<int:id>', views.editOwnerOrders, name='editOwnerOrders'),
    path('deleteOwnerOrders/<int:id>', views.deleteOwnerOrders, name='deleteOwnerOrders'),
    path('showVehicle/<int:id>', views.showVehicle, name='showVehicle'),
    
    # driver
    path('driverVehicleRegister/', login_required(views.driverVehicleRegister.as_view()), name='driverVehicleRegister'),
    path('driverSearchOrder/', views.driverSearchOrder, name='driverSearchOrder'),
    path('vehicleDelete/', views.vehicleDelete, name='vehicleDelete'),
    path('driverConfirmOrder/<int:rid>', views.driverConfirmOrder, name='driverConfirmOrder'),
    
    # owner
    path('ownerRequestOrder/', login_required(views.ownerRequestOrder.as_view()), name='ownerRequestOrder'),

    # sharer
    path('requestSharing/', views.requestSharing, name='requestSharing')
]

web-app/rideSharing/models.py
from ast import mod
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from django.urls.base import reverse


class VehicleType(models.TextChoices):
    SUV = 'SU', _('SUV')
    COMPACT = 'CT', _('Compact')
    SEDAN = 'SD', _('Sedan')
    COUPE = 'CP', _('Coupe')
    OTHER = 'OT', _('Other')


class RideStatus(models.TextChoices):
    OPEN = 'O', _('Open')
    CONFIRMED = 'F', _('Confirmed')
    COMPLETE = 'C', _('Complete')


class Vehicle(models.Model):
    # vehicle-owner
    vehicle_owner = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True, related_name='owner_vehicle')

    # vehicle info
    vehicle_type = models.CharField(max_length=2, choices=VehicleType.choices)
    plate_num = models.CharField(max_length=8)
    seats = models.PositiveIntegerField(default=1)  # 除司机后的可用座位数量
    special_info = models.TextField(max_length=400, blank=True)

    def __str__(self):
        return self.vehicle_type + "Driver: " + self.vehicle_owner.username

    def get_absolute_url(self):
        return reverse('rideSharing-home')


class Ride(models.Model):
    # onwer data
    # the owner of this ride
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    addr = models.CharField(max_length=100)    # destination
    arrive_date = models.DateTimeField(help_text='Format: 2022-01-01 12:00')
    required_type = models.CharField(max_length=2, choices=VehicleType.choices)
    passenger_num = models.PositiveIntegerField(default=1)
    special_requirements = models.CharField(max_length=400, blank=True)
    allow_share = models.BooleanField(default=False)

    # driver data(根据user_name检索)
    driver = models.CharField(default='', max_length=50, blank=True, null=True)

    # sharer data(根据user_name检索)
    sharer = models.CharField(default='', max_length=50, blank=True, null=True)
    sharer_seats = models.PositiveIntegerField(default=0)

    # order status
    status = models.CharField(
        max_length=1, choices=RideStatus.choices, default=RideStatus.OPEN)
    totalRequiredSeats = models.PositiveIntegerField(default=1)  # sharer+owner

    def __str__(self):
        return "owner:" + self.owner.username + " addr: " + self.addr

    # When submit, the webpage will go to the certain place
    def get_absolute_url(self):
        return reverse('rideSharing-home')


'''
IDEA:
所有客户用的都是自带的user数据结构。判断当前user是不是司机，可以去数据库中搜索有没有对应当前user的车。有，则是司机。
ride中owner,driver,sharer都是user类型的。
'''

web-app/rideSharing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import VehicleType


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateRideForm(forms.Form):
    VEHICLE_TYPE_CHOICES = [
        ("SU", "Sedan"),
        ("CT", "Compact"),
        ("SD", "SUV"),
        ("CP", "Coupe"),
        ("OT", "Other")
    ]
    addr = forms.CharField(max_length=100)    # destination
    arrive_date = forms.DateTimeField(help_text='Format: 2022-01-01 12:00')
    required_type = forms.CharField(
        max_length=2, widget=forms.widgets.Select(choices=VEHICLE_TYPE_CHOICES))
    passenger_num = forms.IntegerField(initial=1)
    special_requirements = forms.CharField(max_length=400, required=False)
    allow_share = forms.BooleanField(initial=False, required=False)


class RequestSharingForm(forms.Form):
    addr = forms.CharField(label='Your Destination', max_length=100)
    earlist_time = forms.DateTimeField(label='Earlist Time of Arrival',input_formats='2022-01-01 12:00')
    latest_time = forms.DateTimeField(label='Latest Time of Arrival',input_formats='2022-01-01 12:00')
    special_requirements = forms.CharField(max_length=400, required=False)
    #num_sharer= forms.IntegerField(label='Number of Passengers in your Party')

web-app/rideSharing/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.template import context
from django.views.generic.edit import CreateView
from django.core.mail import send_mail
from django.conf import settings
from .forms import UpdateRideForm, UserRegisterForm, UserUpdateForm, RequestSharingForm
from .models import Ride, RideStatus, Vehicle


# create the register page. usingn register.html template.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'You account have already created. You can login now!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'rideSharing/register.html', {'form': form})


# create home page after login
@login_required
def home(request):
    is_driver = Vehicle.objects.filter(
        vehicle_owner_id=request.user.id).exists()
    if is_driver:
        has_incomplete_rides = Ride.objects.filter(driver=request.user,
                            status=RideStatus.CONFIRMED).exists()
    else:
        has_incomplete_rides = True
    # 创建表单，获取发起request的用户的信息，将form封装成dict传入render
    u_form = UserUpdateForm(instance=request.user)
    context = {
        'u_form': u_form,
        'is_driver': is_driver,
        'has_incomplete_rides': has_incomplete_rides
    }
    return render(request, 'rideSharing/home.html', context=context)

# edit user profile
@login_required
def editProfile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        # Update the forms
        if u_form.is_valid():
            u_form.save()
        # Get feedback to user and redirect them to profile page
        # messages.success(request, f'Your account has been updated!') //useless
        return redirect('editProfile')
    else:
        u_form = UserUpdateForm(instance=request.user)
    context = {
        'u_form': u_form,
    }

    return render(request, 'rideSharing/editProfile.html', context)

############################################################
# myOrders related pages
@login_required
def showAllOrders(request):
    return render(request, 'rideSharing/showAllorders.html')


@login_required
def showOwnerOrders(request):
    # get all the open orders requested by current user
    openRide_list = Ride.objects.filter(
        status=RideStatus.OPEN, owner=request.user)
    openRide_list = openRide_list.order_by('arrive_date')

    # get all the conformed orders requested by current user
    conformed_list = Ride.objects.filter(
        status=RideStatus.CONFIRMED, owner=request.user)
    conformed_list = conformed_list.order_by('arrive_date')

    # get all the complete orders requested by current user
    completedRide_list = Ride.objects.filter(
        status=RideStatus.COMPLETE, owner=request.user)
    completedRide_list = completedRide_list.order_by('arrive_date')

    context = {
        'openRide_list': openRide_list,
        'conformed_list': conformed_list,
        'completedRide_list': completedRide_list
    }

    return render(request, 'rideSharing/showOwnerOrders.html', context=context)


@login_required
def editOwnerOrders(request, id):
    if request.method == "POST":
        ride_form = UpdateRideForm(request.POST)
        if ride_form.is_valid():  # 获取数据
            addr = ride_form.cleaned_data['addr']
            arrive_date = ride_form.cleaned_data['arrive_date']
            required_type = ride_form.cleaned_data['required_type']
            passenger_num = ride_form.cleaned_data['passenger_num']
            special_requirements = ride_form.cleaned_data['special_requirements']
            # create the ride
            cur_ride = Ride.objects.get(id=id)
            cur_ride.addr = addr
            cur_ride.arrive_date = arrive_date
            cur_ride.required_type = required_type
            cur_ride.passenger_num = passenger_num
            cur_ride.special_requirements = special_requirements
            cur_ride.save()
            return redirect('showOwnerOrders')  # 自动跳转回上一层

    ride_form = UpdateRideForm()
    return render(request, 'rideSharing/editOwnerOrders.html', locals())


@login_required
def deleteOwnerOrders(request, id):
    Ride.objects.get(id=id).delete()
    return redirect('showOwnerOrders')  # 自动跳转回上一层


@login_required
def showVehicle(request, id):
    # 通过当前订单的司机名字定位到对应的user,用外键反查到该司机对应的车辆。
    cur_ride = Ride.objects.get(id=id)
    driver_name = cur_ride.driver
    driver = User.objects.filter(username=driver_name).first()
    shownVehicle = driver.owner_vehicle

    context = {
        'shownVehicle': shownVehicle
    }

    return render(request, 'rideSharing/showVehicle.html', context)


@login_required
def showDriverOrders(request):
    # get all the conformed orders requested by current user
    conformed_list = Ride.objects.filter(
        status=RideStatus.CONFIRMED, driver=request.user.username)
    conformed_list = conformed_list.order_by('arrive_date')

    # get all the complete orders requested by current user
    completedRide_list = Ride.objects.filter(
        status=RideStatus.COMPLETE, driver=request.user.username)
    completedRide_list = completedRide_list.order_by('arrive_date')

    context = {
        'conformed_list': conformed_list,
        'completedRide_list': completedRide_list
    }

    return render(request, 'rideSharing/showDriverOrders.html', context=context)


@login_required
def completeDriverOrders(request, id):
    ride = Ride.objects.filter(pk=id).first()
    ride.status = RideStatus.COMPLETE
    ride.save()

    return redirect('showDriverOrders')


@login_required
def showSharerOrders(request):
    # get all the open orders requested by current user
    openRide_list = Ride.objects.filter(
        status=RideStatus.OPEN, sharer=request.user)
    openRide_list = openRide_list.order_by('arrive_date')

    # get all the conformed orders requested by current user
    conformed_list = Ride.objects.filter(
        status=RideStatus.CONFIRMED, sharer=request.user)
    conformed_list = conformed_list.order_by('arrive_date')

    # get all the complete orders requested by current user
    completedRide_list = Ride.objects.filter(
        status=RideStatus.COMPLETE, sharer=request.user)
    completedRide_list = completedRide_list.order_by('arrive_date')

    context = {
        'openRide_list': openRide_list,
        'conformed_list': conformed_list,
        'completedRide_list': completedRide_list
    }

    return render(request, 'rideSharing/showSharerOrders.html', context=context)


############################################################
# Sharer related pages
# request a sharing order. User becomes rider sharer
@login_required
def requestSharing(request):
    if request.method == 'POST':
        joinid = request.POST.get('ride_to_join')
        if joinid is not None:
            ride_to_join = Ride.objects.get(id=joinid)
            ride_to_join.sharer = request.user.username
            ride_to_join.sharer_seats = request.POST.get('n_seats')
            ride_to_join.totalRequiredSeats = ride_to_join.totalRequiredSeats + \
                int(request.POST.get('n_seats'))
            ride_to_join.save()
        joinid = request.POST.get('ride_to_cancel')
        if joinid is not None:
            ride_to_join = Ride.objects.get(id=joinid)
            ride_to_join.sharer = ""
            ride_to_join.totalRequiredSeats = ride_to_join.totalRequiredSeats - \
                ride_to_join.sharer_seats
            ride_to_join.sharer_seats = 0
            ride_to_join.save()

    form = RequestSharingForm(request.GET)
    if form.is_valid():
        show_result = True
        addr = form.cleaned_data.get('addr')
        earlist_time = form.cleaned_data.get('earlist_time')
        latest_time = form.cleaned_data.get('latest_time')
        special_requirements = form.cleaned_data.get('special_requirements')
        #num_sharer = form.cleaned_data.get('num_sharer')
        canidate_list = Ride.objects.filter(
            status=RideStatus.OPEN,
            allow_share=True,
            addr__exact=addr,
            arrive_date__lte=latest_time,
            arrive_date__gte=earlist_time,
            sharer="",
            # driver__seats__gte=F('passenger_num')+num_sharer,
        ).exclude(
            owner=request.user
        )
        if special_requirements != "":
            ride_list = canidate_list.filter(
                special_requirements=special_requirements)
        else:
            ride_list = canidate_list
        # if special_requirements:
        #     ride_list = []
        #     for ride in canidate_list:
        #         car = Vehicle.objects.get(vehicle_owner__username=ride.driver)
        #         if car.special_info == special_requirements:
        #             ride_list.append(ride)
        # else:
        #     ride_list = canidate_list
    else:
        show_result = False
        ride_list = Ride.objects.filter(status=RideStatus.OPEN)

    joined_list = Ride.objects.filter(
        status=RideStatus.OPEN,
        allow_share=True,
        sharer=request.user.username,
    )

    context = {
        'form': form,
        'ride_list': ride_list,
        'joined_list': joined_list,
        'show_result': show_result,
    }
    return render(request, 'rideSharing/requestSharing.html', context=context)


############################################################
# Driver related pages
# driverPage. User registers a vehicle or accepts an order
class driverVehicleRegister(CreateView):
    model = Vehicle
    fields = ['vehicle_type', 'plate_num', 'special_info', 'seats']

web-app/rideSharing/templates/rideSharing/driverSearchOrder.html
<br>
<p>
    Here are all the possible orders you can accept now.
</p>
<p>
    Please choose one and click "accept" link.
</p>
<br>

<table border="1">
    <!-- tr表示每一行， td表示每一个元素 -->
    <thead>
        <tr>
            <!-- tr表示table row， 指一行 -->
            <!-- th相当于是列表的头，告知这一列是什么元素 -->
            <th>Owner</th>
            <th>Request vehicle type</th>
            <th>Destination</th>
            <th>Arrival Time</th>
            <th>Owner's passenger Number</th>
            <th>Share Or Not</th>
            <th>Sharer</th>
            <th>Share seats</th>
            <th>Special Requirement</th>
            <th>Accep Link</th>
        </tr>
    </thead>

    <tbody>
        {% for ride in object_list %}
        <tr>
            <!-- td表示每一行里面的元素 -->
            <td>{{ ride.owner.username }}</td>
            <td>{{ ride.get_required_type_display}}</td>
            <td>{{ ride.addr }}</td>
            <td>{{ ride.arrive_date|date:"m/d/Y P" }}</td>
            <td>{{ ride.passenger_num }}</td>
            <td>{{ ride.allow_share }}</td>
            <td>{{ ride.sharer }}</td>
            <td>{{ ride.sharer_seats }}</td>
            <td>{{ ride.special_requirements }}</td>
            <td><a href="{% url 'driverConfirmOrder' ride.id %}">Accept this order</a></td>

        </tr>
        {% endfor %}
    </tbody>

</table>


<br>
<a href="{% url 'rideSharing-home' %}">
  <button>return</button>
</a>
<br>

web-app/rideSharing/templates/rideSharing/driverVehicleRegister.html
{% extends "rideSharing/base.html" %}
{% block content %}

<div class="content-section">
  <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom md-4">Register your vehicle</legend>
          {{ form.as_p }}
      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Submit</button>
      </div>
  </form>
</div>

<br>
<a href="{% url 'vehicleDelete' %}">
  <button>Delete</button>
</a>
<br>

<br>
<a href="{% url 'rideSharing-home' %}">
  <button>return</button>
</a>
<br>

{% endblock content %}

web-app/rideSharing/templates/rideSharing/editProfile.html
{% extends "rideSharing/base.html" %}

{% block content %}
<div class="content-section">
    <div class="media">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
    <!-- FORM HERE -->
    <!-- Change the encoding of the form data: multipart, to make sure the image is properly saved -->
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Profile Info</legend>
          {{ u_form }}
      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Update</button>
      </div>
  </form>
  </div>

<br>
<a href="{% url 'rideSharing-home' %}">
  <button>return</button>
</a>
<br>
{% endblock content %}

web-app/rideSharing/templates/rideSharing/logout.html
{% extends "rideSharing/base.html" %}
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

web-app/rideSharing/templates/rideSharing/requestSharing.html
{% extends "rideSharing/base.html" %}
{% block content %}

<div class="container">
  <h3 class="text-muted">Hello, {{user.username}}</h3>

  <div class="mb-3">
    <form action="#" method="get">
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Search your ride below.</legend>
        <div class="row">
          {% for field in form %}
          <div class="row mb-3">
            <div class="col-sm-2">
              {{ field.label_tag }}
            </div>
            <div class="col-sm-4">
              {{ field }}
            </div>
          </div>
          {% endfor %}
        </div>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Search</button>
      </div>
    </form>
  </div>

  {% if show_result %}
  <legend class="border-bottom mb-4">Available Rides:</legend>
  {% if ride_list.exists %}
  <table class="table table-striped table-hover table-responsive">
    <thead>
      <tr>
        <th>Status</th>
        <th>Owner</th>
        <th>Address</th>
        <th>Arrival Time</th>
        <th>Sharer</th>
      </tr>
    </thead>
    <tbody>
      {% for ride in ride_list %}
      <tr>
        <td>{{ ride.get_status_display }}</td>
        <td>{{ ride.owner.username }}</td>
        <td>{{ ride.addr }}</td>
        <td>{{ ride.arrive_date }}</td>
        <td>
          <form action="" method=post>
            {% csrf_token %}
            <div class="col col-sm-4">
              <div class="input-group">
                <input type="hidden" name="ride_to_join" value="{{ ride.id }}" />
                <input name="n_seats" type="number" min="1" required class="form-control" placeholder="# seats"
                  aria-label="Recipient's username" aria-describedby="button-addon2">
                <button type="submit" class="btn btn-outline-primary" id="button-addon2">Button</button>
              </div>
            </div>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No ride available.</p>
  {% endif %}
  {% endif %}

  <legend class="border-bottom mb-4">Joined Rides:</legend>
  {% if joined_list.exists %}
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Status</th>
        <th>Owner</th>
        <th>Address</th>
        <th>Arrival Time</th>
        <th>Your Seats</th>
        <th>Sharer</th>
      </tr>
    </thead>
    <tbody>
      {% for ride in joined_list %}
      <tr>
        <td>{{ ride.get_status_display }}</td>
        <td>{{ ride.owner.username }}</td>
        <td>{{ ride.addr }}</td>
        <td>{{ ride.arrive_date }}</td>
        <td>{{ ride.sharer_seats }}</td>
        <td>
          <form action="" method=post>
            {% csrf_token %}
            <button name="ride_to_cancel" value="{{ ride.id }}" class="btn btn-outline-danger">Cancel</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>Nothing.</p>
  {% endif %}
</div>
{% endblock content %}

web-app/rideSharing/templates/rideSharing/showDriverOrders.html
{% extends "rideSharing/base.html" %}
{% block content %}

<div class="container">
    <br>
    <p>
        Here are all the orders you request.
    </p>
    <br>

    <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                    data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true"
                    aria-controls="panelsStayOpen-collapseOne">
                    Confirmed orders:
                </button>
            </h2>
            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show"
                aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <table class="table table-striped table-hover table-responsive">
                        <!-- tr表示每一行， td表示每一个元素 -->
                        <thead>
                            <tr>
                                <!-- tr表示table row， 指一行 -->
                                <!-- th相当于是列表的头，告知这一列是什么元素 -->
                                <th>Owner</th>
                                <th>Request vehicle type</th>
                                <th>Destination</th>
                                <th>Arrival Time</th>
                                <th>Owner's passenger Number</th>
                                <th>Share Or Not</th>
                                <th>Sharer</th>
                                <th>Share seats</th>
                                <th>Special Requirement</th>
                                <th>Driver</th>
                                <th>Finish Order</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for ride in conformed_list %}
                            <tr>
                                <!-- td表示每一行里面的元素 -->
                                <td>{{ ride.owner.username }}</td>
                                <td>{{ ride.get_required_type_display}}</td>
                                <td>{{ ride.addr }}</td>
                                <td>{{ ride.arrive_date|date:"m/d/Y P" }}</td>
                                <td>{{ ride.passenger_num }}</td>
                                <td>{{ ride.allow_share }}</td>
                                <td>{{ ride.sharer }}</td>
                                <td>{{ ride.sharer_seats }}</td>
                                <td>{{ ride.special_requirements }}</td>
                                <td>{{ ride.driver }}</td>
                                <td><a href="{% url 'completeDriverOrders' ride.id %}" class="btn btn-outline-success" role="button">Complete</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false"
                    aria-controls="panelsStayOpen-collapseTwo">
                    Completed orders:
                </button>
            </h2>
            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse"
                aria-labelledby="panelsStayOpen-headingTwo" data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <table border="1">
                        <!-- tr表示每一行， td表示每一个元素 -->
                        <thead>
                            <tr>
                                <!-- tr表示table row， 指一行 -->
                                <!-- th相当于是列表的头，告知这一列是什么元素 -->
                                <th>Owner</th>
                                <th>Request vehicle type</th>
                                <th>Destination</th>
                                <th>Arrival Time</th>
                                <th>Owner's passenger Number</th>
                                <th>Share Or Not</th>
                                <th>Sharer</th>
                                <th>Share seats</th>
                                <th>Special Requirement</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for ride in completedRide_list %}
                            <tr>
                                <!-- td表示每一行里面的元素 -->
                                <td>{{ ride.owner.username }}</td>
                                <td>{{ ride.get_required_type_display}}</td>
                                <td>{{ ride.addr }}</td>
                                <td>{{ ride.arrive_date|date:"m/d/Y P" }}</td>
                                <td>{{ ride.passenger_num }}</td>
                                <td>{{ ride.allow_share }}</td>
                                <td>{{ ride.sharer }}</td>
                                <td>{{ ride.sharer_seats }}</td>
                                <td>{{ ride.special_requirements }}</td>

                            </tr>
                            {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>



    <br>
    <a href="{% url 'showAllOrders' %}">
        <button>return</button>
    </a>
    <br>
</div>
{% endblock content %}

web-app/rideSharing/templates/rideSharing/showVehicle.html
<br>
<p>
    Here are the vehicle information you request.
</p>
<br>

<table border="1">
    <!-- tr表示每一行， td表示每一个元素 -->
    <thead>
        <tr>
            <!-- tr表示table row， 指一行 -->
            <!-- th相当于是列表的头，告知这一列是什么元素 -->
            <th>Owner</th>
            <th>vehicle_type</th>
            <th>plate_num</th>
            <th>seats</th>
            <th>special_info</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <!-- td表示每一行里面的元素 -->
            <td>{{ shownVehicle.vehicle_owner.username }}</td>
            <td>{{ shownVehicle.get_vehicle_type_display}}</td>
            <td>{{ shownVehicle.plate_num }}</td>
            <td>{{ shownVehicle.seats }}</td>
            <td>{{ shownVehicle.special_info }}</td>
        </tr>
    </tbody>

</table>

<br>
<a href="{% url 'showOwnerOrders' %}">
  <button>return</button>
</a>
<br>